# Changes here will be overwritten by Copier
_commit: v1.3.4
_src_path: gh:lincc-frameworks/python-project-template
author_email: robert.nikutta@gmail.com
author_name: Robert Nikutta
create_example_module: true
custom_install: true
include_notebooks: true
mypy_type_checking: basic
package_name: grappa
preferred_linter: pylint
project_license: BSD
project_name: astrograppa
use_gitlfs: none
use_isort: true
